
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: May 20 2026 23:26:52 +07 (May 20 2026 16:26:52 UTC)

// Verification Directory fv/SPI_Top 

module SPI_Top(REFCLK, MASTER_INPUT, MASTER_CNTL, n_rst0,
     SLAVE0_DATA_IN, SLAVE0_LOAD, SLAVE0_DATA_OUT, SLAVE0_RX_DONE,
     n_rst1, SLAVE1_DATA_IN, SLAVE1_LOAD, SLAVE1_DATA_OUT,
     SLAVE1_RX_DONE, MASTER_OUTPUT, MASTER_READY, MASTER_VALID, SS);
  input REFCLK, n_rst0, SLAVE0_LOAD, n_rst1, SLAVE1_LOAD;
  input [7:0] MASTER_INPUT, SLAVE0_DATA_IN, SLAVE1_DATA_IN;
  input [1:0] MASTER_CNTL;
  output [7:0] SLAVE0_DATA_OUT, SLAVE1_DATA_OUT, MASTER_OUTPUT;
  output SLAVE0_RX_DONE, SLAVE1_RX_DONE, MASTER_READY, MASTER_VALID;
  output [1:0] SS;
  wire REFCLK, n_rst0, SLAVE0_LOAD, n_rst1, SLAVE1_LOAD;
  wire [7:0] MASTER_INPUT, SLAVE0_DATA_IN, SLAVE1_DATA_IN;
  wire [1:0] MASTER_CNTL;
  wire [7:0] SLAVE0_DATA_OUT, SLAVE1_DATA_OUT, MASTER_OUTPUT;
  wire SLAVE0_RX_DONE, SLAVE1_RX_DONE, MASTER_READY, MASTER_VALID;
  wire [1:0] SS;
  wire [4:0] u_master_u_crc5_checker_current_crc;
  wire [4:0] u_slave1_tx_crc_out;
  wire [4:0] u_slave0_tx_crc_out;
  wire [3:0] u_slave1_counter;
  wire [3:0] u_slave0_counter;
  wire [7:0] u_slave1_MISO_Block_buffer;
  wire [7:0] u_slave0_MISO_Block_buffer;
  wire [1:0] u_master_state;
  wire [4:0] u_master_crc_out;
  wire [3:0] u_master_count;
  wire [7:0] u_master_u_buf_P2S_buffer;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_125, n_126, n_127, n_129, n_131, n_132;
  wire n_133, n_134, n_135, n_136, n_137, n_138, n_139, n_140;
  wire n_141, n_142, n_143, n_144, n_145, n_146, n_147, n_148;
  wire n_149, n_150, n_151, n_152, n_153, n_154, n_155, n_156;
  wire n_157, n_158, n_159, n_160, n_161, n_162, n_163, n_164;
  wire n_165, n_166, n_167, n_206, n_219, u_master_out_buf_P2S,
       u_slave0_tx_miso_data, u_slave1_tx_miso_data;
  SDFFRHQX1 \u_master_u_crc5_checker_u_crc5_crc_out_reg[2] (.RN
       (n_167), .CK (n_166), .D
       (u_master_u_crc5_checker_current_crc[2]), .SI (n_165), .SE
       (n_167), .Q (u_master_u_crc5_checker_current_crc[2]));
  SDFFRHQX1 \u_master_u_crc5_checker_u_crc5_crc_out_reg[0] (.RN
       (n_167), .CK (n_166), .D
       (u_master_u_crc5_checker_current_crc[0]), .SI (n_164), .SE
       (n_167), .Q (u_master_u_crc5_checker_current_crc[0]));
  CLKXOR2X1 g3422__2398(.A (u_master_u_crc5_checker_current_crc[1]), .B
       (n_164), .Y (n_165));
  SDFFRHQX1 \u_slave1_tx_crc_calc_crc_out_reg[2] (.RN (n_162), .CK
       (n_166), .D (u_slave1_tx_crc_out[2]), .SI (n_158), .SE (n_161),
       .Q (u_slave1_tx_crc_out[2]));
  SDFFRHQX1 \u_slave0_tx_crc_calc_crc_out_reg[2] (.RN (n_160), .CK
       (n_166), .D (u_slave0_tx_crc_out[2]), .SI (n_156), .SE (n_159),
       .Q (u_slave0_tx_crc_out[2]));
  SDFFQX1 \u_master_u_buf_S2P_buffer_reg[7] (.CK (n_166), .D (n_163),
       .SI (MASTER_OUTPUT[7]), .SE (n_150), .Q (MASTER_OUTPUT[7]));
  CLKXOR2X1 g3426__5107(.A (u_master_u_crc5_checker_current_crc[4]), .B
       (n_163), .Y (n_164));
  SDFFRHQX1 \u_slave1_tx_crc_calc_crc_out_reg[0] (.RN (n_162), .CK
       (n_166), .D (u_slave1_tx_crc_out[0]), .SI (n_157), .SE (n_161),
       .Q (u_slave1_tx_crc_out[0]));
  SDFFRHQX1 \u_slave0_tx_crc_calc_crc_out_reg[0] (.RN (n_160), .CK
       (n_166), .D (u_slave0_tx_crc_out[0]), .SI (n_155), .SE (n_159),
       .Q (u_slave0_tx_crc_out[0]));
  CLKXOR2X1 g3429__6260(.A (u_slave1_tx_crc_out[1]), .B (n_157), .Y
       (n_158));
  CLKXOR2X1 g3430__4319(.A (u_slave0_tx_crc_out[1]), .B (n_155), .Y
       (n_156));
  TBUFX1 u_slave0_g8__8428(.A (n_153), .OE (n_87), .Y (n_163));
  TBUFX1 u_slave1_g8__5526(.A (n_154), .OE (n_36), .Y (n_163));
  AO22X1 g3432__6783(.A0 (u_slave1_tx_miso_data), .A1 (n_43), .B0
       (u_slave1_counter[3]), .B1 (n_143), .Y (n_154));
  CLKXOR2X1 g3433__3680(.A (u_slave1_tx_miso_data), .B
       (u_slave1_tx_crc_out[4]), .Y (n_157));
  AO22X1 g3431__1617(.A0 (u_slave0_tx_miso_data), .A1 (n_67), .B0
       (u_slave0_counter[3]), .B1 (n_131), .Y (n_153));
  CLKXOR2X1 g3434__2802(.A (u_slave0_tx_miso_data), .B
       (u_slave0_tx_crc_out[4]), .Y (n_155));
  DFFNSRX1 \u_slave1_MISO_Block_buffer_reg[0] (.RN (n_27), .SN (n_10),
       .CKN (n_166), .D (u_slave1_MISO_Block_buffer[1]), .Q
       (u_slave1_tx_miso_data), .QN (UNCONNECTED));
  DFFNSRX1 \u_slave0_MISO_Block_buffer_reg[0] (.RN (n_33), .SN (n_7),
       .CKN (n_166), .D (u_slave0_MISO_Block_buffer[1]), .Q
       (u_slave0_tx_miso_data), .QN (UNCONNECTED0));
  SDFFQX1 \u_slave1_MOSI_Block_buffer_reg[7] (.CK (n_166), .D
       (SLAVE1_DATA_OUT[7]), .SI (n_152), .SE (n_161), .Q
       (SLAVE1_DATA_OUT[7]));
  SDFFQX1 \u_slave0_MOSI_Block_buffer_reg[7] (.CK (n_166), .D
       (SLAVE0_DATA_OUT[7]), .SI (n_152), .SE (n_159), .Q
       (SLAVE0_DATA_OUT[7]));
  DFFNSRX1 \u_slave0_MISO_Block_buffer_reg[1] (.RN (n_34), .SN (n_21),
       .CKN (n_166), .D (u_slave0_MISO_Block_buffer[2]), .Q
       (u_slave0_MISO_Block_buffer[1]), .QN (UNCONNECTED1));
  DFFNSRX1 \u_slave1_MISO_Block_buffer_reg[1] (.RN (n_17), .SN (n_35),
       .CKN (n_166), .D (u_slave1_MISO_Block_buffer[2]), .Q
       (u_slave1_MISO_Block_buffer[1]), .QN (UNCONNECTED2));
  DFFNSRX1 \u_slave1_MISO_Block_buffer_reg[2] (.RN (n_32), .SN (n_16),
       .CKN (n_166), .D (u_slave1_MISO_Block_buffer[3]), .Q
       (u_slave1_MISO_Block_buffer[2]), .QN (UNCONNECTED3));
  DFFNSRX1 \u_slave0_MISO_Block_buffer_reg[2] (.RN (n_23), .SN (n_30),
       .CKN (n_166), .D (u_slave0_MISO_Block_buffer[3]), .Q
       (u_slave0_MISO_Block_buffer[2]), .QN (UNCONNECTED4));
  OR2X1 g3449__1705(.A (u_master_state[0]), .B (n_151), .Y (n_152));
  DFFNSRX1 \u_slave1_MISO_Block_buffer_reg[3] (.RN (n_28), .SN (n_5),
       .CKN (n_166), .D (u_slave1_MISO_Block_buffer[4]), .Q
       (u_slave1_MISO_Block_buffer[3]), .QN (UNCONNECTED5));
  DFFNSRX1 \u_slave0_MISO_Block_buffer_reg[3] (.RN (n_13), .SN (n_14),
       .CKN (n_166), .D (u_slave0_MISO_Block_buffer[4]), .Q
       (u_slave0_MISO_Block_buffer[3]), .QN (UNCONNECTED6));
  MX2X1 g3465__5122(.A (u_master_out_buf_P2S), .B (n_149), .S0 (n_147),
       .Y (n_151));
  SDFFQX1 \u_master_u_buf_S2P_buffer_reg[0] (.CK (n_166), .D
       (MASTER_OUTPUT[1]), .SI (MASTER_OUTPUT[0]), .SE (n_150), .Q
       (MASTER_OUTPUT[0]));
  SDFFRHQX1 \u_master_u_crc5_crc_out_reg[2] (.RN (n_167), .CK (n_166),
       .D (n_66), .SI (u_master_crc_out[2]), .SE (n_150), .Q
       (u_master_crc_out[2]));
  SDFFRHQX1 \u_master_u_crc5_crc_out_reg[0] (.RN (n_167), .CK (n_166),
       .D (n_65), .SI (u_master_crc_out[0]), .SE (n_150), .Q
       (u_master_crc_out[0]));
  SDFFRHQX1 \u_master_u_crc5_crc_out_reg[4] (.RN (n_167), .CK (n_166),
       .D (u_master_crc_out[3]), .SI (u_master_crc_out[4]), .SE
       (n_150), .Q (u_master_crc_out[4]));
  SDFFRHQX1 \u_master_u_crc5_crc_out_reg[1] (.RN (n_167), .CK (n_166),
       .D (u_master_crc_out[0]), .SI (u_master_crc_out[1]), .SE
       (n_150), .Q (u_master_crc_out[1]));
  SDFFQX1 \u_master_u_buf_S2P_buffer_reg[4] (.CK (n_166), .D
       (MASTER_OUTPUT[5]), .SI (MASTER_OUTPUT[4]), .SE (n_150), .Q
       (MASTER_OUTPUT[4]));
  SDFFRHQX1 \u_master_u_crc5_crc_out_reg[3] (.RN (n_167), .CK (n_166),
       .D (u_master_crc_out[2]), .SI (u_master_crc_out[3]), .SE
       (n_150), .Q (u_master_crc_out[3]));
  DFFNSRX1 \u_slave0_MISO_Block_buffer_reg[4] (.RN (n_11), .SN (n_4),
       .CKN (n_166), .D (u_slave0_MISO_Block_buffer[5]), .Q
       (u_slave0_MISO_Block_buffer[4]), .QN (UNCONNECTED7));
  DFFNSRX1 \u_slave1_MISO_Block_buffer_reg[4] (.RN (n_8), .SN (n_24),
       .CKN (n_166), .D (u_slave1_MISO_Block_buffer[5]), .Q
       (u_slave1_MISO_Block_buffer[4]), .QN (UNCONNECTED8));
  SDFFQX1 \u_master_u_buf_S2P_buffer_reg[6] (.CK (n_166), .D
       (MASTER_OUTPUT[7]), .SI (MASTER_OUTPUT[6]), .SE (n_150), .Q
       (MASTER_OUTPUT[6]));
  SDFFQX1 \u_master_u_buf_S2P_buffer_reg[3] (.CK (n_166), .D
       (MASTER_OUTPUT[4]), .SI (MASTER_OUTPUT[3]), .SE (n_150), .Q
       (MASTER_OUTPUT[3]));
  SDFFQX1 \u_master_u_buf_S2P_buffer_reg[1] (.CK (n_166), .D
       (MASTER_OUTPUT[2]), .SI (MASTER_OUTPUT[1]), .SE (n_150), .Q
       (MASTER_OUTPUT[1]));
  DFFHQX1 \u_master_count_reg[3] (.CK (REFCLK), .D (n_148), .Q
       (u_master_count[3]));
  SDFFQX1 \u_master_u_buf_S2P_buffer_reg[5] (.CK (n_166), .D
       (MASTER_OUTPUT[6]), .SI (MASTER_OUTPUT[5]), .SE (n_150), .Q
       (MASTER_OUTPUT[5]));
  SDFFQX1 \u_master_u_buf_S2P_buffer_reg[2] (.CK (n_166), .D
       (MASTER_OUTPUT[3]), .SI (MASTER_OUTPUT[2]), .SE (n_150), .Q
       (MASTER_OUTPUT[2]));
  SDFFRHQX1 \u_slave1_tx_crc_calc_crc_out_reg[4] (.RN (n_162), .CK
       (n_166), .D (u_slave1_tx_crc_out[4]), .SI
       (u_slave1_tx_crc_out[3]), .SE (n_161), .Q
       (u_slave1_tx_crc_out[4]));
  SDFFRHQX1 \u_slave1_tx_crc_calc_crc_out_reg[3] (.RN (n_162), .CK
       (n_166), .D (u_slave1_tx_crc_out[3]), .SI
       (u_slave1_tx_crc_out[2]), .SE (n_161), .Q
       (u_slave1_tx_crc_out[3]));
  SDFFQX1 \u_slave1_MOSI_Block_buffer_reg[3] (.CK (n_166), .D
       (SLAVE1_DATA_OUT[3]), .SI (SLAVE1_DATA_OUT[4]), .SE (n_161), .Q
       (SLAVE1_DATA_OUT[3]));
  SDFFRHQX1 \u_slave1_tx_crc_calc_crc_out_reg[1] (.RN (n_162), .CK
       (n_166), .D (u_slave1_tx_crc_out[1]), .SI
       (u_slave1_tx_crc_out[0]), .SE (n_161), .Q
       (u_slave1_tx_crc_out[1]));
  SDFFQX1 \u_slave1_MOSI_Block_buffer_reg[5] (.CK (n_166), .D
       (SLAVE1_DATA_OUT[5]), .SI (SLAVE1_DATA_OUT[6]), .SE (n_161), .Q
       (SLAVE1_DATA_OUT[5]));
  SDFFQX1 \u_slave1_MOSI_Block_buffer_reg[0] (.CK (n_166), .D
       (SLAVE1_DATA_OUT[0]), .SI (SLAVE1_DATA_OUT[1]), .SE (n_161), .Q
       (SLAVE1_DATA_OUT[0]));
  SDFFQX1 \u_slave1_MOSI_Block_buffer_reg[1] (.CK (n_166), .D
       (SLAVE1_DATA_OUT[1]), .SI (SLAVE1_DATA_OUT[2]), .SE (n_161), .Q
       (SLAVE1_DATA_OUT[1]));
  SDFFQX1 \u_slave1_MOSI_Block_buffer_reg[6] (.CK (n_166), .D
       (SLAVE1_DATA_OUT[6]), .SI (SLAVE1_DATA_OUT[7]), .SE (n_161), .Q
       (SLAVE1_DATA_OUT[6]));
  SDFFQX1 \u_slave1_MOSI_Block_buffer_reg[4] (.CK (n_166), .D
       (SLAVE1_DATA_OUT[4]), .SI (SLAVE1_DATA_OUT[5]), .SE (n_161), .Q
       (SLAVE1_DATA_OUT[4]));
  SDFFQX1 \u_slave1_MOSI_Block_buffer_reg[2] (.CK (n_166), .D
       (SLAVE1_DATA_OUT[2]), .SI (SLAVE1_DATA_OUT[3]), .SE (n_161), .Q
       (SLAVE1_DATA_OUT[2]));
  OAI21X1 g3490__8246(.A0 (n_50), .A1 (n_141), .B0 (n_142), .Y (n_149));
  DFFHQX1 \u_master_count_reg[2] (.CK (REFCLK), .D (n_145), .Q
       (u_master_count[2]));
  AO22X1 g3475__7098(.A0 (n_58), .A1 (n_147), .B0 (u_master_count[3]),
       .B1 (n_144), .Y (n_148));
  DFFNSRX1 \u_slave0_MISO_Block_buffer_reg[5] (.RN (n_22), .SN (n_12),
       .CKN (n_166), .D (u_slave0_MISO_Block_buffer[6]), .Q
       (u_slave0_MISO_Block_buffer[5]), .QN (UNCONNECTED9));
  DFFNSRX1 \u_slave1_MISO_Block_buffer_reg[5] (.RN (n_3), .SN (n_6),
       .CKN (n_166), .D (u_slave1_MISO_Block_buffer[6]), .Q
       (u_slave1_MISO_Block_buffer[5]), .QN (UNCONNECTED10));
  SDFFQX1 \u_master_SS_reg[0] (.CK (REFCLK), .D (n_113), .SI (SS[0]),
       .SE (n_146), .Q (SS[0]));
  DFFHQX1 \u_master_count_reg[1] (.CK (REFCLK), .D (n_138), .Q
       (u_master_count[1]));
  SDFFQX1 \u_master_SS_reg[1] (.CK (REFCLK), .D (n_109), .SI (SS[1]),
       .SE (n_146), .Q (SS[1]));
  OAI2BB1X1 g3491__6131(.A0N (u_master_count[2]), .A1N (n_144), .B0
       (n_125), .Y (n_145));
  DFFNSRX1 \u_master_u_buf_P2S_buffer_reg[5] (.RN (n_77), .SN (n_103),
       .CKN (n_166), .D (n_132), .Q (u_master_u_buf_P2S_buffer[4]), .QN
       (UNCONNECTED11));
  DFFNSRX1 \u_master_u_buf_P2S_buffer_reg[2] (.RN (n_81), .SN (n_99),
       .CKN (n_166), .D (n_116), .Q (u_master_u_buf_P2S_buffer[1]), .QN
       (UNCONNECTED12));
  SDFFQX1 \u_slave0_MOSI_Block_buffer_reg[0] (.CK (n_166), .D
       (SLAVE0_DATA_OUT[0]), .SI (SLAVE0_DATA_OUT[1]), .SE (n_159), .Q
       (SLAVE0_DATA_OUT[0]));
  SDFFRHQX1 \u_slave0_tx_crc_calc_crc_out_reg[4] (.RN (n_160), .CK
       (n_166), .D (u_slave0_tx_crc_out[4]), .SI
       (u_slave0_tx_crc_out[3]), .SE (n_159), .Q
       (u_slave0_tx_crc_out[4]));
  SDFFQX1 \u_slave0_MOSI_Block_buffer_reg[1] (.CK (n_166), .D
       (SLAVE0_DATA_OUT[1]), .SI (SLAVE0_DATA_OUT[2]), .SE (n_159), .Q
       (SLAVE0_DATA_OUT[1]));
  SDFFQX1 \u_slave0_MOSI_Block_buffer_reg[3] (.CK (n_166), .D
       (SLAVE0_DATA_OUT[3]), .SI (SLAVE0_DATA_OUT[4]), .SE (n_159), .Q
       (SLAVE0_DATA_OUT[3]));
  SDFFQX1 \u_slave0_MOSI_Block_buffer_reg[2] (.CK (n_166), .D
       (SLAVE0_DATA_OUT[2]), .SI (SLAVE0_DATA_OUT[3]), .SE (n_159), .Q
       (SLAVE0_DATA_OUT[2]));
  SDFFQX1 \u_slave0_MOSI_Block_buffer_reg[6] (.CK (n_166), .D
       (SLAVE0_DATA_OUT[6]), .SI (SLAVE0_DATA_OUT[7]), .SE (n_159), .Q
       (SLAVE0_DATA_OUT[6]));
  SDFFQX1 \u_slave0_MOSI_Block_buffer_reg[5] (.CK (n_166), .D
       (SLAVE0_DATA_OUT[5]), .SI (SLAVE0_DATA_OUT[6]), .SE (n_159), .Q
       (SLAVE0_DATA_OUT[5]));
  SDFFRHQX1 \u_slave0_tx_crc_calc_crc_out_reg[3] (.RN (n_160), .CK
       (n_166), .D (u_slave0_tx_crc_out[3]), .SI
       (u_slave0_tx_crc_out[2]), .SE (n_159), .Q
       (u_slave0_tx_crc_out[3]));
  DFFRHQX1 \u_slave0_counter_reg[2] (.RN (n_139), .CK (n_166), .D
       (n_126), .Q (u_slave0_counter[2]));
  DFFRHQX1 \u_slave1_counter_reg[3] (.RN (n_134), .CK (n_166), .D
       (n_120), .Q (u_slave1_counter[3]));
  OA22X1 g3496__1881(.A0 (n_90), .A1 (n_140), .B0 (n_121), .B1 (n_129),
       .Y (n_150));
  OAI211X1 g3487__5115(.A0 (u_slave1_counter[0]), .A1 (n_64), .B0
       (n_53), .C0 (n_96), .Y (n_143));
  AOI32X1 g3512__7482(.A0 (u_master_count[0]), .A1
       (u_master_crc_out[2]), .A2 (n_137), .B0 (n_141), .B1 (n_110), .Y
       (n_142));
  DFFNSRX1 \u_slave0_MISO_Block_buffer_reg[6] (.RN (n_20), .SN (n_29),
       .CKN (n_166), .D (u_slave0_MISO_Block_buffer[7]), .Q
       (u_slave0_MISO_Block_buffer[6]), .QN (UNCONNECTED13));
  DFFNSRX1 \u_slave1_MISO_Block_buffer_reg[6] (.RN (n_15), .SN (n_9),
       .CKN (n_166), .D (u_slave1_MISO_Block_buffer[7]), .Q
       (u_slave1_MISO_Block_buffer[6]), .QN (UNCONNECTED14));
  DFFNSRX1 \u_master_u_buf_P2S_buffer_reg[7] (.RN (n_76), .SN (n_101),
       .CKN (n_166), .D (n_114), .Q (u_master_u_buf_P2S_buffer[7]), .QN
       (UNCONNECTED15));
  DFFNSRX1 \u_master_u_buf_P2S_buffer_reg[4] (.RN (n_79), .SN (n_107),
       .CKN (n_166), .D (n_133), .Q (u_master_u_buf_P2S_buffer[3]), .QN
       (UNCONNECTED16));
  DFFNSRX1 \u_master_u_buf_P2S_buffer_reg[1] (.RN (n_83), .SN (n_104),
       .CKN (n_166), .D (n_117), .Q (u_master_u_buf_P2S_buffer[0]), .QN
       (UNCONNECTED17));
  DFFNSRX1 \u_master_u_buf_P2S_buffer_reg[3] (.RN (n_80), .SN (n_102),
       .CKN (n_166), .D (n_115), .Q (u_master_u_buf_P2S_buffer[2]), .QN
       (UNCONNECTED18));
  DFFNSRX1 \u_master_u_buf_P2S_buffer_reg[6] (.RN (n_78), .SN (n_100),
       .CKN (n_166), .D (n_119), .Q (u_master_u_buf_P2S_buffer[5]), .QN
       (UNCONNECTED19));
  SDFFQX1 \u_slave0_MOSI_Block_buffer_reg[4] (.CK (n_166), .D
       (SLAVE0_DATA_OUT[4]), .SI (SLAVE0_DATA_OUT[5]), .SE (n_159), .Q
       (SLAVE0_DATA_OUT[4]));
  SDFFRHQX1 \u_slave0_tx_crc_calc_crc_out_reg[1] (.RN (n_160), .CK
       (n_166), .D (u_slave0_tx_crc_out[1]), .SI
       (u_slave0_tx_crc_out[0]), .SE (n_159), .Q
       (u_slave0_tx_crc_out[1]));
  DFFNSRX1 \u_master_u_buf_P2S_buffer_reg[0] (.RN (n_84), .SN (n_106),
       .CKN (n_166), .D (n_118), .Q (u_master_out_buf_P2S), .QN
       (UNCONNECTED20));
  SDFFQX1 \u_master_count_reg[0] (.CK (REFCLK), .D (n_136), .SI
       (n_135), .SE (u_master_count[0]), .Q (u_master_count[0]));
  DFFHQX1 \u_master_state_reg[0] (.CK (REFCLK), .D (n_123), .Q
       (u_master_state[0]));
  AND2X1 g3516__4733(.A (u_master_state[1]), .B (n_140), .Y (n_147));
  SDFFRHQX1 \u_master_u_crc5_checker_u_crc5_crc_out_reg[1] (.RN
       (n_167), .CK (n_166), .D
       (u_master_u_crc5_checker_current_crc[1]), .SI
       (u_master_u_crc5_checker_current_crc[0]), .SE (n_167), .Q
       (u_master_u_crc5_checker_current_crc[1]));
  SDFFRHQX1 \u_master_u_crc5_checker_u_crc5_crc_out_reg[3] (.RN
       (n_167), .CK (n_166), .D
       (u_master_u_crc5_checker_current_crc[3]), .SI
       (u_master_u_crc5_checker_current_crc[2]), .SE (n_167), .Q
       (u_master_u_crc5_checker_current_crc[3]));
  AO22X1 g3537__6161(.A0 (n_137), .A1 (n_136), .B0 (u_master_count[1]),
       .B1 (n_135), .Y (n_138));
  SDFFRHQX1 \u_master_u_crc5_checker_u_crc5_crc_out_reg[4] (.RN
       (n_167), .CK (n_166), .D
       (u_master_u_crc5_checker_current_crc[4]), .SI
       (u_master_u_crc5_checker_current_crc[3]), .SE (n_167), .Q
       (u_master_u_crc5_checker_current_crc[4]));
  AOI21X2 g3520__9315(.A0 (u_slave1_counter[3]), .A1 (n_127), .B0
       (SS[1]), .Y (n_161));
  MX2X1 g3543__9945(.A (u_master_u_buf_P2S_buffer[3]), .B
       (u_master_u_buf_P2S_buffer[4]), .S0 (n_167), .Y (n_133));
  MX2X1 g3544__2883(.A (u_master_u_buf_P2S_buffer[4]), .B
       (u_master_u_buf_P2S_buffer[5]), .S0 (n_167), .Y (n_132));
  OAI31X1 g3509__2346(.A0 (u_slave0_counter[2]), .A1
       (u_slave0_counter[1]), .A2 (n_37), .B0 (n_75), .Y (n_131));
  OAI211X1 g3474__1666(.A0 (u_master_state[0]), .A1 (n_59), .B0
       (n_122), .C0 (n_129), .Y (MASTER_VALID));
  NOR2BX1 g3533__7410(.AN (u_slave1_counter[3]), .B (n_127), .Y
       (SLAVE1_RX_DONE));
  DFFRHQX1 \u_slave0_counter_reg[1] (.RN (n_139), .CK (n_166), .D
       (n_92), .Q (u_slave0_counter[1]));
  DFFHQX1 \u_master_state_reg[1] (.CK (REFCLK), .D (n_91), .Q
       (u_master_state[1]));
  DFFRHQX1 \u_slave1_counter_reg[0] (.RN (n_134), .CK (n_166), .D
       (n_94), .Q (u_slave1_counter[0]));
  DFFNSRX1 \u_slave0_MISO_Block_buffer_reg[7] (.RN (n_31), .SN (n_18),
       .CKN (n_166), .D (1'b0), .Q (u_slave0_MISO_Block_buffer[7]), .QN
       (UNCONNECTED21));
  NOR2BX1 g3511__6417(.AN (n_111), .B (n_95), .Y (n_126));
  OAI21X1 g3513__5477(.A0 (n_73), .A1 (n_72), .B0 (n_85), .Y (n_125));
  DFFNSRX1 \u_slave1_MISO_Block_buffer_reg[7] (.RN (n_25), .SN (n_19),
       .CKN (n_166), .D (1'b0), .Q (u_slave1_MISO_Block_buffer[7]), .QN
       (UNCONNECTED22));
  AOI21X1 g3523__2398(.A0 (n_122), .A1 (n_60), .B0 (n_121), .Y (n_123));
  OA21X1 g3510__5107(.A0 (u_slave1_counter[3]), .A1 (n_69), .B0 (n_97),
       .Y (n_120));
  MX2X1 g3538__6260(.A (u_master_u_buf_P2S_buffer[5]), .B
       (u_master_u_buf_P2S_buffer[7]), .S0 (n_167), .Y (n_119));
  MX2X1 g3539__4319(.A (u_master_out_buf_P2S), .B
       (u_master_u_buf_P2S_buffer[0]), .S0 (n_167), .Y (n_118));
  MX2X1 g3540__8428(.A (u_master_u_buf_P2S_buffer[0]), .B
       (u_master_u_buf_P2S_buffer[1]), .S0 (n_167), .Y (n_117));
  MX2X1 g3541__5526(.A (u_master_u_buf_P2S_buffer[1]), .B
       (u_master_u_buf_P2S_buffer[2]), .S0 (n_167), .Y (n_116));
  MX2X1 g3542__6783(.A (u_master_u_buf_P2S_buffer[2]), .B
       (u_master_u_buf_P2S_buffer[3]), .S0 (n_167), .Y (n_115));
  NOR2BX1 g3551__3680(.AN (u_master_u_buf_P2S_buffer[7]), .B (n_167),
       .Y (n_114));
  NAND2BX1 g3489__1617(.AN (MASTER_INPUT[0]), .B (n_108), .Y (n_113));
  AND2X1 g3555__2802(.A (n_68), .B (n_111), .Y (n_112));
  OAI2BB1X1 g3557__1705(.A0N (u_master_crc_out[1]), .A1N (n_49), .B0
       (n_63), .Y (n_110));
  NAND2X1 g3488__5122(.A (MASTER_INPUT[0]), .B (n_108), .Y (n_109));
  NAND2XL g3563__8246(.A (MASTER_INPUT[4]), .B (n_105), .Y (n_107));
  NAND2XL g3565__7098(.A (MASTER_INPUT[0]), .B (n_105), .Y (n_106));
  NAND2XL g3566__6131(.A (MASTER_INPUT[1]), .B (n_105), .Y (n_104));
  NAND2XL g3580__1881(.A (MASTER_INPUT[5]), .B (n_105), .Y (n_103));
  NAND2XL g3571__5115(.A (MASTER_INPUT[3]), .B (n_105), .Y (n_102));
  NAND2XL g3572__7482(.A (MASTER_INPUT[7]), .B (n_105), .Y (n_101));
  NAND2XL g3575__4733(.A (MASTER_INPUT[6]), .B (n_105), .Y (n_100));
  NAND2XL g3569__6161(.A (MASTER_INPUT[2]), .B (n_105), .Y (n_99));
  AND2X1 g3521__9315(.A (n_97), .B (n_70), .Y (n_98));
  NAND3BXL g3534__9945(.AN (u_slave1_counter[2]), .B
       (u_slave1_tx_crc_out[3]), .C (n_88), .Y (n_96));
  OR2X1 g3526__2883(.A (u_master_count[3]), .B (n_71), .Y (n_140));
  XNOR2X1 g3545__2346(.A (u_slave0_counter[2]), .B (n_74), .Y (n_95));
  NAND2X1 g3548__1666(.A (u_slave1_counter[0]), .B (n_97), .Y (n_94));
  NOR2BX1 g3549__7410(.AN (n_97), .B (n_57), .Y (n_93));
  AND2X1 g3550__6417(.A (n_54), .B (n_111), .Y (n_92));
  OAI22X1 g3556__5477(.A0 (n_90), .A1 (n_86), .B0 (n_121), .B1 (n_144),
       .Y (n_91));
  NAND2X1 g3552__2398(.A (u_slave0_counter[0]), .B (n_111), .Y (n_89));
  NAND2X1 g3553__5107(.A (u_slave1_counter[2]), .B (n_88), .Y (n_127));
  OA21X1 g3559__6260(.A0 (n_56), .A1 (n_61), .B0 (n_87), .Y (n_159));
  OA21X1 g3560__4319(.A0 (REFCLK), .A1 (n_86), .B0 (n_85), .Y (n_166));
  OR2XL g3564__8428(.A (n_82), .B (MASTER_INPUT[0]), .Y (n_84));
  OR2XL g3567__5526(.A (n_82), .B (MASTER_INPUT[1]), .Y (n_83));
  OR2XL g3568__6783(.A (n_82), .B (MASTER_INPUT[2]), .Y (n_81));
  OR2XL g3570__3680(.A (n_82), .B (MASTER_INPUT[3]), .Y (n_80));
  OR2XL g3573__1617(.A (n_82), .B (MASTER_INPUT[4]), .Y (n_79));
  OR2XL g3574__2802(.A (n_82), .B (MASTER_INPUT[6]), .Y (n_78));
  OR2XL g3579__1705(.A (n_82), .B (MASTER_INPUT[5]), .Y (n_77));
  OR2XL g3584__5122(.A (n_82), .B (MASTER_INPUT[7]), .Y (n_76));
  AOI22X1 g3536__8246(.A0 (n_1), .A1 (n_40), .B0
       (u_slave0_tx_crc_out[1]), .B1 (n_74), .Y (n_75));
  AO21X1 g3586__7098(.A0 (n_85), .A1 (n_73), .B0 (n_144), .Y (n_135));
  ADDHX1 g3546__6131(.A (u_master_count[2]), .B (n_48), .CO (n_71), .S
       (n_72));
  ADDHX1 g3547__1881(.A (u_slave1_counter[2]), .B (n_52), .CO (n_69),
       .S (n_70));
  OAI2BB1X1 g3576__5115(.A0N (u_slave0_counter[1]), .A1N (n_38), .B0
       (n_67), .Y (n_68));
  CLKXOR2X1 g3554__7482(.A (u_master_crc_out[1]), .B (n_65), .Y (n_66));
  MX2X1 g3558__4733(.A (n_45), .B (n_44), .S0 (u_slave1_counter[1]), .Y
       (n_64));
  NAND2BX1 g3577__6161(.AN (n_137), .B (u_master_crc_out[0]), .Y
       (n_63));
  NOR4X1 g3514__9315(.A (MASTER_INPUT[5]), .B (MASTER_INPUT[7]), .C
       (MASTER_INPUT[6]), .D (n_42), .Y (n_108));
  AND2X1 g3578__9945(.A (u_slave0_counter[3]), .B (n_61), .Y
       (SLAVE0_RX_DONE));
  NAND2X1 g3581__2883(.A (n_85), .B (n_86), .Y (n_60));
  OA21X1 g3535__2346(.A0 (u_master_u_crc5_checker_current_crc[4]), .A1
       (n_46), .B0 (n_86), .Y (n_59));
  INVXL g3598(.A (n_82), .Y (n_105));
  OA21X1 g3589__1666(.A0 (n_41), .A1 (u_master_state[1]), .B0 (n_58),
       .Y (n_167));
  ADDHX1 g3562__7410(.A (u_slave1_counter[0]), .B (n_2), .CO (n_88), .S
       (n_57));
  XNOR2X1 g3585__6417(.A (u_master_count[2]), .B (n_47), .Y (n_141));
  AO21X1 g3588__5477(.A0 (n_26), .A1 (n_51), .B0 (n_56), .Y (n_111));
  OR2X1 g3587__2398(.A (n_0), .B (n_39), .Y (n_97));
  NOR2X1 g3595__5107(.A (n_90), .B (n_73), .Y (n_136));
  NAND3BXL g3605__6260(.AN (MASTER_CNTL[0]), .B (MASTER_CNTL[1]), .C
       (MASTER_READY), .Y (n_146));
  NAND3BX1 g3606__4319(.AN (MASTER_CNTL[1]), .B (MASTER_CNTL[0]), .C
       (MASTER_READY), .Y (n_82));
  ADDHX1 g3561__8428(.A (u_slave0_counter[0]), .B
       (u_slave0_counter[1]), .CO (n_74), .S (n_54));
  NAND2X1 g3592__5526(.A (u_slave1_tx_crc_out[1]), .B (n_52), .Y
       (n_53));
  NOR2X1 g3594__6783(.A (u_slave0_counter[1]), .B (n_51), .Y (n_61));
  NAND2X1 g3593__3680(.A (u_slave0_counter[3]), .B (n_51), .Y (n_67));
  MXI2XL g3600__1617(.A (u_master_crc_out[4]), .B
       (u_master_crc_out[3]), .S0 (n_49), .Y (n_50));
  NOR2X1 g3596__2802(.A (n_48), .B (n_47), .Y (n_137));
  AND2X1 g3597__1705(.A (n_73), .B (n_47), .Y (n_86));
  INVX1 g3609(.A (n_90), .Y (n_85));
  OR4X1 g3582__5122(.A (u_master_u_crc5_checker_current_crc[0]), .B
       (u_master_u_crc5_checker_current_crc[2]), .C
       (u_master_u_crc5_checker_current_crc[3]), .D
       (u_master_u_crc5_checker_current_crc[1]), .Y (n_46));
  MXI2XL g3599__8246(.A (u_slave1_tx_crc_out[4]), .B
       (u_slave1_tx_crc_out[0]), .S0 (u_slave1_counter[2]), .Y (n_45));
  AOI21X1 g3591__7098(.A0 (u_slave1_counter[2]), .A1
       (u_slave1_tx_crc_out[0]), .B0 (u_slave1_tx_crc_out[2]), .Y
       (n_44));
  OAI2BB1X1 g3590__6131(.A0N (u_slave1_counter[0]), .A1N
       (u_slave1_counter[2]), .B0 (u_slave1_counter[3]), .Y (n_43));
  OR4X1 g3583__1881(.A (MASTER_INPUT[1]), .B (MASTER_INPUT[2]), .C
       (MASTER_INPUT[3]), .D (MASTER_INPUT[4]), .Y (n_42));
  INVX1 g3608(.A (MASTER_READY), .Y (n_129));
  NAND2X1 g3632__5115(.A (u_master_state[1]), .B (n_58), .Y (n_90));
  NOR2X1 g3656__7482(.A (u_master_state[1]), .B (n_58), .Y (n_144));
  INVXL g3607(.A (n_121), .Y (n_41));
  AO22X1 g3602__4733(.A0 (u_slave0_tx_crc_out[2]), .A1
       (u_slave0_counter[1]), .B0 (u_slave0_counter[2]), .B1
       (u_slave0_tx_crc_out[0]), .Y (n_40));
  OAI21X1 g3603__6161(.A0 (u_slave1_counter[0]), .A1
       (u_slave1_counter[1]), .B0 (u_slave1_counter[3]), .Y (n_39));
  INVX1 g3633(.A (n_51), .Y (n_38));
  MXI2XL g3601__9315(.A (u_slave0_tx_crc_out[4]), .B
       (u_slave0_tx_crc_out[3]), .S0 (u_slave0_counter[0]), .Y (n_37));
  CLKXOR2X1 g3604__9945(.A (u_master_crc_out[4]), .B
       (u_master_out_buf_P2S), .Y (n_65));
  AND2XL g3626__2883(.A (n_36), .B (n_rst1), .Y (n_134));
  AND2XL g3628__2346(.A (n_87), .B (n_rst0), .Y (n_139));
  NAND2XL g3619__1666(.A (n_206), .B (SLAVE1_DATA_IN[1]), .Y (n_35));
  NAND2BXL g3648__7410(.AN (SLAVE0_DATA_IN[1]), .B (n_219), .Y (n_34));
  NAND2BXL g3646__6417(.AN (SLAVE0_DATA_IN[0]), .B (SLAVE0_LOAD), .Y
       (n_33));
  NAND2BXL g3651__5477(.AN (SLAVE1_DATA_IN[2]), .B (n_206), .Y (n_32));
  NAND2BXL g3618__2398(.AN (SLAVE0_DATA_IN[7]), .B (n_219), .Y (n_31));
  NAND2XL g3652__5107(.A (n_219), .B (SLAVE0_DATA_IN[2]), .Y (n_30));
  NAND2XL g3615__6260(.A (SLAVE0_LOAD), .B (SLAVE0_DATA_IN[6]), .Y
       (n_29));
  NAND2BXL g3617__4319(.AN (SLAVE1_DATA_IN[3]), .B (n_206), .Y (n_28));
  NAND2BXL g3616__8428(.AN (SLAVE1_DATA_IN[0]), .B (SLAVE1_LOAD), .Y
       (n_27));
  NAND2X1 g3614__5526(.A (u_slave0_counter[2]), .B
       (u_slave0_counter[1]), .Y (n_26));
  NAND2BXL g3613__6783(.AN (SLAVE1_DATA_IN[7]), .B (n_206), .Y (n_25));
  NAND2XL g3612__3680(.A (SLAVE1_LOAD), .B (SLAVE1_DATA_IN[4]), .Y
       (n_24));
  NAND2BXL g3610__1617(.AN (SLAVE0_DATA_IN[2]), .B (SLAVE0_LOAD), .Y
       (n_23));
  NAND2BXL g3611__2802(.AN (SLAVE0_DATA_IN[5]), .B (n_219), .Y (n_22));
  AND2X1 g3629__1705(.A (u_slave1_counter[0]), .B
       (u_slave1_counter[1]), .Y (n_52));
  AND2X1 g3627__5122(.A (u_master_count[0]), .B (u_master_count[1]), .Y
       (n_48));
  NOR2X1 g3654__8246(.A (u_master_count[0]), .B (u_master_count[1]), .Y
       (n_47));
  AND2X1 g3653__7098(.A (u_master_count[3]), .B (u_master_count[2]), .Y
       (n_73));
  NAND2X1 g3655__6131(.A (u_slave0_counter[2]), .B
       (u_slave0_counter[0]), .Y (n_51));
  NOR2BX1 g3657__1881(.AN (n_rst0), .B (SLAVE0_LOAD), .Y (n_160));
  NOR2BX1 g3631__5115(.AN (n_rst1), .B (SLAVE1_LOAD), .Y (n_162));
  NAND2XL g3638__7482(.A (SLAVE0_LOAD), .B (SLAVE0_DATA_IN[1]), .Y
       (n_21));
  NAND2BXL g3621__4733(.AN (SLAVE0_DATA_IN[6]), .B (n_219), .Y (n_20));
  NAND2XL g3622__6161(.A (n_206), .B (SLAVE1_DATA_IN[7]), .Y (n_19));
  NAND2XL g3623__9315(.A (SLAVE0_LOAD), .B (SLAVE0_DATA_IN[7]), .Y
       (n_18));
  NAND2BXL g3650__9945(.AN (SLAVE1_DATA_IN[1]), .B (n_206), .Y (n_17));
  NAND2XL g3649__2883(.A (SLAVE1_LOAD), .B (SLAVE1_DATA_IN[2]), .Y
       (n_16));
  NAND2BXL g3647__2346(.AN (SLAVE1_DATA_IN[6]), .B (SLAVE1_LOAD), .Y
       (n_15));
  NAND2XL g3634__1666(.A (n_219), .B (SLAVE0_DATA_IN[3]), .Y (n_14));
  NAND2BXL g3635__7410(.AN (SLAVE0_DATA_IN[3]), .B (n_219), .Y (n_13));
  NAND2XL g3636__6417(.A (n_219), .B (SLAVE0_DATA_IN[5]), .Y (n_12));
  NAND2BXL g3637__5477(.AN (SLAVE0_DATA_IN[4]), .B (SLAVE0_LOAD), .Y
       (n_11));
  NAND2XL g3620__2398(.A (n_206), .B (SLAVE1_DATA_IN[0]), .Y (n_10));
  NAND2XL g3639__5107(.A (SLAVE1_LOAD), .B (SLAVE1_DATA_IN[6]), .Y
       (n_9));
  NAND2BXL g3640__6260(.AN (SLAVE1_DATA_IN[4]), .B (SLAVE1_LOAD), .Y
       (n_8));
  NAND2XL g3641__4319(.A (n_219), .B (SLAVE0_DATA_IN[0]), .Y (n_7));
  NAND2XL g3642__8428(.A (SLAVE1_LOAD), .B (SLAVE1_DATA_IN[5]), .Y
       (n_6));
  NAND2XL g3643__5526(.A (n_206), .B (SLAVE1_DATA_IN[3]), .Y (n_5));
  NAND2XL g3644__6783(.A (SLAVE0_LOAD), .B (SLAVE0_DATA_IN[4]), .Y
       (n_4));
  NAND2BXL g3645__3680(.AN (SLAVE1_DATA_IN[5]), .B (n_206), .Y (n_3));
  NAND2X1 g3624__1617(.A (u_master_state[1]), .B (u_master_state[0]),
       .Y (n_122));
  NAND2X1 g3625__2802(.A (MASTER_CNTL[0]), .B (MASTER_CNTL[1]), .Y
       (n_121));
  INVX1 g3660(.A (SS[1]), .Y (n_36));
  INVX1 g3662(.A (u_master_state[0]), .Y (n_58));
  INVX1 g3664(.A (u_master_count[0]), .Y (n_49));
  INVX1 g3658(.A (SS[0]), .Y (n_87));
  BUFX2 drc_buf_sp3756(.A (SLAVE1_LOAD), .Y (n_206));
  BUFX2 drc_buf_sp3768(.A (SLAVE0_LOAD), .Y (n_219));
  DFFRX1 \u_slave1_counter_reg[1] (.RN (n_134), .CK (n_166), .D (n_93),
       .Q (u_slave1_counter[1]), .QN (n_2));
  DFFRX1 \u_slave0_counter_reg[3] (.RN (n_139), .CK (n_166), .D
       (n_112), .Q (u_slave0_counter[3]), .QN (n_56));
  DFFRX1 \u_slave0_counter_reg[0] (.RN (n_139), .CK (n_166), .D (n_89),
       .Q (u_slave0_counter[0]), .QN (n_1));
  DFFRX1 \u_slave1_counter_reg[2] (.RN (n_134), .CK (n_166), .D (n_98),
       .Q (u_slave1_counter[2]), .QN (n_0));
  NOR2X1 g3630__3783(.A (u_master_state[1]), .B (u_master_state[0]), .Y
       (MASTER_READY));
endmodule

